### ISSUE TITLE
Can this EFI run BigSur?(这个EFI可以启动bigsur嘛)

### ISSUE THREAD

**Issue by AkinaHaruka** [tamht298/Hackintosh-OpenCore-EFI-Dell-Inspiron-5559#5]
Can this EFI run BigSur?(这个EFI可以启动bigsur嘛)

**Comment by tamht298** [comment]
Maybe, I haven't checked it. But I think it will be fine

**Comment by AkinaHaruka** [comment]
I have tryed but it's panic,thank you
