### ISSUE TITLE
Ethernet Cable not working on Catalina

### ISSUE THREAD

**Issue by Sharaf-Mansour** [tamht298/Hackintosh-OpenCore-EFI-Dell-Inspiron-5559#6]
I am trying to connect to internet via Ethernet Cable. 
It does not work.
Wi-Fi Is working but Cable is not.
On windows Cable was working fine.
Is there a way to fix that ? Or do I have to reinstall MacOS ?

**Comment by tamht298** [comment]
Maybe you can download ethernet kext here https://www.reddit.com/r/hackintosh/comments/aw1rdl/kexts_for_realtek_pcie_gbe_family_controller/

I have not ethernet cable, so I didn't add them into kexts
